server:
  port: 9000
spring:
  application:
    name: eureka-demo1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/
#      defaultZone: http://eureka-demo3:9001/eureka/
